# Generated by Django 3.2.8 on 2022-01-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Title', models.CharField(max_length=50)),
                ('Course_Description', models.CharField(max_length=500)),
                ('Course_Tutor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(verbose_name='Lecture Date')),
                ('LD_Img', models.ImageField(upload_to='LectureDayImgs')),
                ('LectureBoardFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LectureBoard.lectureboard')),
            ],
        ),
        migrations.CreateModel(
            name='SlidePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DownloadLink', models.CharField(max_length=200)),
                ('ProcSlidePack', models.CharField(max_length=200)),
                ('LectureDayFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LectureBoard.lectureday')),
            ],
        ),
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModDate', models.DateTimeField(verbose_name='Modification Date')),
                ('VersionNum', models.IntegerField()),
                ('Comment', models.CharField(max_length=300)),
                ('SlidePackFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LectureBoard.slidepack')),
            ],
        ),
    ]
