# Generated by Django 3.2.8 on 2022-02-09 13:40

import LectureBoard.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.CharField(blank=True, max_length=2000)),
                ('Date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Lecture Date')),
                ('LD_Img', models.ImageField(blank=True, upload_to='LectureDayImgs')),
            ],
        ),
        migrations.CreateModel(
            name='SlidePack',
            fields=[
                ('OriginalFile', models.FileField(blank=True, upload_to='SlidePacks/original', validators=[LectureBoard.models.Data_Validators.validate_file_extension, LectureBoard.models.Data_Validators.validate_file_size])),
                ('OnlineSlidePack', models.FileField(blank=True, upload_to='SlidePacks/online')),
                ('SlidePack_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('LectureDay_FK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='LectureBoard.lectureday')),
            ],
        ),
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModDate', models.DateTimeField(verbose_name='Modification Date')),
                ('VersionNum', models.IntegerField()),
                ('Comment', models.CharField(blank=True, max_length=300)),
                ('SlidePackFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LectureBoard.slidepack')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_Code', models.CharField(max_length=10)),
                ('Module_Title', models.CharField(max_length=50)),
                ('Module_Description', models.CharField(blank=True, max_length=2000)),
                ('Module_Tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Module Tutor')),
            ],
        ),
        migrations.AddField(
            model_name='lectureday',
            name='ModuleLectureBoard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LectureBoard.module'),
        ),
    ]
