# Generated by Django 3.2.8 on 2022-01-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LectureBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectureday',
            old_name='LectureBoardFK',
            new_name='ModuleLectureBoard',
        ),
        migrations.AlterField(
            model_name='lectureboard',
            name='Course_Description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='lectureday',
            name='Description',
            field=models.CharField(max_length=2000),
        ),
    ]
